-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1440@144",
    position = "0x0",
    scale = "1",
    vrr = 1,
})

-- monitor = DP-2,     2560x1440@144,  0x0,        1,  vrr,  1
-- monitor = HDMI-A-2, 1920x1080@60,   -1920x0,    1
-- monitor = HDMI-A-1, 1920x1080@60,   -960x-1080, 1

 -- monitorv2 {
 --     output = eDP-1
 --     mode = 2560x1440@144
 --     position = 0x0
 --     scale = 1
 --     transform = 0
 --     supports_wide_color = 0
 --     supports_hdr = 0
 -- }

-- monitorv2 {
--     output = DP-2
--     mode = 2560x1440@144
--     position = 1x1
--     scale = 1
--     transform = 0
--     supports_wide_color = 1
--     bitdepth = 10
--     sdr_min_luminance = 0.005
-- }

-- monitorv2 {
--     output = HDMI-A-2
--     mode = 1920x1080@60
--     position = -1920x0
--     scale = 1
--     transform = 0
--     supports_wide_color = 0
--     supports_hdr = 0
-- }
--
-- monitorv2 {
--     output = HDMI-A-1
--     mode = 1920x1080@60
--     position = -960x-1080
--     scale = 1
--     transform = 0
--     supports_wide_color = 0
--     supports_hdr = 0
-- }

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch
-- exec-once = hyprpm reload -n
--# Custom scripts

-- Set programs that you use
local terminal = "kitty"
local menu = "fuzzel --anchor=top --lines=20 --tabs=5 --layer=overlay"

hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })
hl.curve("easeInQuad", { type = "bezier", points = { { 0.5, 0.5 }, { 0.5, 0.5 } } })
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 5,
    bezier = "easeOutCirc",
    style = "popin 60%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 5,
    bezier = "easeOutCirc",
    style = "slide",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 6,
    bezier = "easeOutCirc",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 6,
    bezier = "easeOutCirc",
    style = "slide",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 20,
    bezier = "easeInQuad",
    style = "loop",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 5,
    bezier = "easeOutCirc",
})

hl.device({
    name = "logitech-g502-hero-se",
})

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  hyprbars { ... }
  borders-plus-plus { ... }
]]

-- Source: ~/.config/hypr/hyprSources/hyprWindowRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprSources.hyprWindowRules")

-- Source: ~/.config/hypr/hyprSources/hyprKeymappings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprSources.hyprKeymappings")

-- Source: ~/.config/hypr/hyprSources/hyprWorkspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprSources.hyprWorkspaces")

-- Source: ~/.config/hypr/hyprSources/hyprEnvirs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprSources.hyprEnvirs")
hl.config({
    cursor = {
        no_hardware_cursors = true,
        enable_hyprcursor = true,
        default_monitor = "\"DP-2\"",
    },
    -- For all categories, see https://wiki.hyprland.org/Configuring/Variables/
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:swapescape",
        kb_rules = "",
        numlock_by_default = true,
        repeat_rate = 80,
        repeat_delay = 300,
        sensitivity = 0, -- -1.0 to 1.0, 0 means no modification.
        accel_profile = "\"flat\"",
        force_no_accel = false,
        left_handed = false,
        scroll_points = "",
        scroll_button = 0,
        follow_mouse = 2,
        focus_on_close = 0,
        float_switch_override_focus = 2,
        emulate_discrete_scroll = 2, -- 0 disables it, 1 enables handling of non-standard events only, and 2 force enables all scroll wheel events to be handled
        touchpad = {
            natural_scroll = true,
            middle_button_emulation = false, -- true
            drag_lock = true,
        },
    },
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        border_size = 2,
        gaps_in = 5,
        gaps_out = 5,
        gaps_workspaces = 50,
        col = {
            active_border = { colors = { "rgba(a50b5eff)", "rgba(00000000)" }, angle = 45 }, -- rgba(0ba552ff) 45deg
            inactive_border = "rgba(928374ff)",
        },
        resize_on_border = true,
        hover_icon_on_border = true,
        layout = "dwindle",
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = true,
    },
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 5,
        active_opacity = 1,
        inactive_opacity = 1,
        fullscreen_opacity = 1,
        dim_inactive = true,
        dim_strength = 0.40,
        dim_special = 0.5,
        blur = {
            enabled = true,
            size = 1,
            passes = 5,
            ignore_opacity = false, -- true
            new_optimizations = true,
            xray = true,
            noise = 0.0,
            contrast = 0.7,
            brightness = 0.8,
            vibrancy = 0.1,
            vibrancy_darkness = 0.1,
            special = false,
            popups = false, -- true
        },
    },
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        -- pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- you probably want this
        special_scale_factor = 0.95,
    },
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        mfact = 0.75,
        new_on_top = true,
        new_on_active = "before",
        orientation = "left",
        -- always_center_master = true
        drop_at_cursor = true,
    },
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    },
    misc = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        font_family = "CascadiaCodeNF",
        splash_font_family = "CascadiaCodeNF",
        force_default_wallpaper = -1,
        -- vfr = true
        vrr = 1,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        always_follow_on_dnd = false,
        layers_hog_keyboard_focus = true,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        enable_swallow = true,
        focus_on_activate = false,
        mouse_move_focuses_monitor = false,
        background_color = 0x000000,
    },
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    debug = {
        overlay = false,
        damage_blink = false,
        damage_tracking = 2,
        disable_logs = false,
    },
    -- bind = CTRL, TAB, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable
    -- Window rules
    -- Keymappings
    -- Workspace binds and assignment
    -- ---Env vars---
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 15")
    hl.exec_cmd("waybar")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("xwaylandvideobridge")
end)

