-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 21

-- TODO: manual review — unknown section 'listener {' on line 26

-- TODO: manual review — unknown section 'listener {' on line 32
hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock", -- avoid starting multiple hyprlock instances.
        before_sleep_cmd = "loginctl lock-session", -- lock before suspend.
        after_sleep_cmd = "hyprctl dispatch dpms on", -- to avoid having to press a key twice to turn on the display.
        ignore_dbus_inhibit = false, -- whether to ignore dbus-sent idle inhibit events (e.g. from firefox)
    },
    -- listener {
    --   timeout = 150                                # 2.5min.
    --   on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    --   on-resume = brightnessctl -r                 # monitor backlight restore.
    -- }
    -- turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
    -- listener { 
    --   timeout = 150                                          # 2.5min.
    --   on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight.
    --   on-resume = brightnessctl -rd rgb:kbd_backlight        # turn on keyboard backlight.
    -- }
})

