-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'preload = ~/Pictures/wallpaps/small.png' has no enclosing section

-- wallpaper = eDP-1,~/Pictures/wallpaps/mtns.jpg
-- TODO: manual review — top-level key 'wallpaper = DP-2,~/Pictures/wallpaps/small.png' has no enclosing section
-- TODO: manual review — top-level key 'wallpaper = HDMI-A-2,~/Pictures/wallpaps/small.png' has no enclosing section

-- TODO: manual review — unexpected token after 'unload all'
