-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'background {' on line 12
-- all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations

-- TODO: manual review — unknown section 'input-field {' on line 57

-- TODO: manual review — unknown section 'label {' on line 94
hl.config({
    general = {
        grace = 5,
        no_fade_in = false,
        no_fade_out = false,
        immediate_render = false,
        text_trim = true,
        fractional_scaling = 2,
    },
    -- Widgets #
    -- image {
    --   monitor =
    --   size = 150 # lesser side if not 1:1 ratio
    --   rounding = -1 # negative values mean circle
    --   border_size = 4
    --   border_color = rgb(221, 221, 221)
    --   rotate = 0 # degrees, counter-clockwise
    --   reload_time = -1 # seconds between reloading, 0 to reload with SIGUSR2
    --   reload_cmd =  # command to get new path. if empty, old path will be used. don't run "follow" commands like tail -F
    --
    --   position = 0, 200
    --   halign = center
    --   valign = center
    -- }
    -- shape {
    --   monitor =
    --   size = 200, 50
    --   color = rgba(17, 17, 17, 1.0)
    --   rounding = -1
    --   border_size = 8
    --   border_color = rgba(0, 207, 230, 1.0)
    --   rotate = 0
    --   xray = true # if true, make a "hole" in the background (rectangle of specified size, no rotation)
    --
    --   position = 0, 80
    --   halign = center
    --   valign = center
    -- }
})

