-- Config wkspcs 1-10
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "7",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "8",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "9",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "10",
    monitor = "eDP-1",
})

-- Config wkspcs 1-10
hl.workspace_rule({
    workspace = "11",
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "12",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "13",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "14",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "15",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "16",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "17",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "18",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "19",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "20",
    monitor = "eDP-1",
})

-- Config wkspcs 1-10
hl.workspace_rule({
    workspace = "31",
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "32",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "33",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "34",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "35",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "36",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "37",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "38",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "39",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "40",
    monitor = "eDP-1",
})

local mainMod = "SUPER"

-- Move workspaces
-- DP
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- HDMI
hl.bind(mainMod .. " + ALT + 1", hl.dsp.focus({ workspace = 11 }))
hl.bind(mainMod .. " + ALT + 2", hl.dsp.focus({ workspace = 12 }))
hl.bind(mainMod .. " + ALT + 3", hl.dsp.focus({ workspace = 13 }))
hl.bind(mainMod .. " + ALT + 4", hl.dsp.focus({ workspace = 14 }))
hl.bind(mainMod .. " + ALT + 5", hl.dsp.focus({ workspace = 15 }))
hl.bind(mainMod .. " + ALT + 6", hl.dsp.focus({ workspace = 16 }))
hl.bind(mainMod .. " + ALT + 7", hl.dsp.focus({ workspace = 17 }))
hl.bind(mainMod .. " + ALT + 8", hl.dsp.focus({ workspace = 18 }))
hl.bind(mainMod .. " + ALT + 9", hl.dsp.focus({ workspace = 19 }))
hl.bind(mainMod .. " + ALT + 0", hl.dsp.focus({ workspace = 20 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + ALT + 1", hl.dsp.window.move({ workspace = 11 }))
hl.bind(mainMod .. " + SHIFT + ALT + 2", hl.dsp.window.move({ workspace = 12 }))
hl.bind(mainMod .. " + SHIFT + ALT + 3", hl.dsp.window.move({ workspace = 13 }))
hl.bind(mainMod .. " + SHIFT + ALT + 4", hl.dsp.window.move({ workspace = 14 }))
hl.bind(mainMod .. " + SHIFT + ALT + 5", hl.dsp.window.move({ workspace = 15 }))
hl.bind(mainMod .. " + SHIFT + ALT + 6", hl.dsp.window.move({ workspace = 16 }))
hl.bind(mainMod .. " + SHIFT + ALT + 7", hl.dsp.window.move({ workspace = 17 }))
hl.bind(mainMod .. " + SHIFT + ALT + 8", hl.dsp.window.move({ workspace = 18 }))
hl.bind(mainMod .. " + SHIFT + ALT + 9", hl.dsp.window.move({ workspace = 19 }))
hl.bind(mainMod .. " + SHIFT + ALT + 0", hl.dsp.window.move({ workspace = 20 }))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("Secret1"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:Secret1", follow = false }))
hl.bind(mainMod .. " + ALT + S", hl.dsp.workspace.toggle_special("Secret2"))
hl.bind(mainMod .. " + ALT + SHIFT + S", hl.dsp.window.move({ workspace = "special:Secret2", follow = false }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
