-- ---Env vars---
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("WLR_NO_HARDWARE_CURSORS", "1")

-- XDG specs
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- Qt vars
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")

-- Toolkit backend
-- env = GDK_BACKEND,wayland,  x11
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
-- env = SDL_VIDEODRIVER,      wayland,x11
hl.env("CLUTTER_BACKEND", "wayland")

-- Hyprcursor
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "15")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "15")
-- env = GTK_THEME, Sweet-Dark-v40
