-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.exit())
-- bind = $mainMod, E, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable
hl.bind(mainMod .. " + t", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("fuzzel --anchor=top --lines=20 --tabs=5 --layer=overlay"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
-- bind = $mainMod ALT, L, togglesplit, # dwindle
hl.bind(mainMod .. " + CTRL + V", hl.dsp.exec_cmd("kitty --class clipse -e 'clipse'"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("refreshWallpaper"))

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))

-- Waybar reload
hl.bind(mainMod .. " + ALT + k", hl.dsp.exec_cmd("killall waybar; waybar"))

-- Media key mappings
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.config/dunst/volumeNotifs.sh up"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.config/dunst/volumeNotifs.sh down"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.config/dunst/volumeNotifs.sh mute"), { locked = true })

-- Bind brightness keys with brightnessctl
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"))
