"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$time\
[](fg:color_bg1 bg:color_blue)\
$sudo\
$username\
[](bg:color_bg2 fg:color_blue)\
$character\
[](fg:color_bg2) \
 """ # $os $character"""

right_format = """
[](fg:color_purple)\
$directory\
[](fg:color_orange bg:color_purple)\
$git_branch\
$git_status\
[](fg:color_bg1 bg:color_orange)\
$docker_context\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$zig\
[](bg:color_bg1 fg:color_bg2)\
$cmd_duration\
[](fg:color_bg2)\
"""

palette = 'tokyonight'

[palettes.tokyonight]
color_fg0 = '#c0caf5'
color_fg1 = '#a9b1d6'
color_bg1 = '#15161e'
color_bg2 = '#665c54'
color_blue = '#7aa2f7'
color_aqua = '#7dcfff'
color_green = '#9ece6a'
color_orange = '#ff9e64'
color_purple = '#bb9af7'
color_red = '#f7768e'
color_yellow = '#e0af68'

[os]
disabled = false
style = "bg:color_bg2 fg:color_blue"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇 "
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false                                           # true
style_user = "bg:color_blue fg:color_bg1"
style_root = "bg:color_orange fg:color_red"
format = '[ $user ]($style)'
aliases = { "fmart" = "SirCaljerque", "placeholder" = "jaz" }

[sudo]
symbol = "󰡗 "
disabled = false
style = "bg:color_blue fg:color_bg1"
format = "[ $symbol]($style)"

[localip]
ssh_only = true
style = "bg:color_blue fg:color_bg1"
format = "[@$localipv4]($style) "

[directory]
style = "fg:color_bg1 bg:color_purple"
format = "[ $path ]($style)"
read_only = ''
truncation_length = 6
truncation_symbol = "…/"

[directory.substitutions]
"/Documents" = "/󰈙"
"/Downloads" = "/ "
"/Music" = "/󰝚 "
"/Pictures" = "/ "
"/Code" = "/󰲋 "
"/Certs" = "/󰄤 "
"/Apps" = "/󰀻"
"/Dots" = "/󱞞 "

[direnv]
disabled = true # false

[git_branch]
symbol = ""
style = "bg:color_orange fg:color_bg1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_orange fg:color_bg1"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg1 fg:color_yellow"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = " "
style = "bg:color_bg1 fg:color_aqua"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "bg:color_bg1 fg:color_orange"
format = '[ $symbol( $version) ]($style)'

[zig]
symbol = " "
style = "bg:color_bg1 fg:color_yellow"
format = '[ $symbol( $version) ]($style)'
detect_extensions = ['zig']

[golang]
symbol = ""
style = "bg:color_bg1 fg:color_aqua"
format = '[ $symbol ]($style)'

[php]
symbol = " "
style = "bg:color_bg1 fg:color_purple"
format = '[ $symbol ]($style)'

[java]
symbol = " "
style = "bg:color_bg1 fg:color_green"
format = '[ $symbol ]($style)'

[kotlin]
symbol = " "
style = "bg:color_bg1 fg:color_green"
format = '[ $symbol ]($style)'

[haskell]
symbol = " "
style = "bg:color_bg1 fg:color_purple"
format = '[ $symbol]($style)'

[python]
symbol = " "
style = "bg:color_bg1 fg:color_blue"
format = '[ $symbol( $version) $virtualenv ]($style)'

[docker_context]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[$time ](fg:color_fg0 bg:color_bg1)]($style)'

[cmd_duration]
show_milliseconds = true
min_time = 0
style = 'bg:color_bg2 fg:color_fg0'
format = '[ 󰚭$duration ]($style)'

[line_break]
disabled = false

# [character]
# disabled = false
# success_symbol = '[](bold fg:color_green)'
# error_symbol = '[](bold fg:color_red)'
# vimcmd_symbol = '[](bold fg:color_green)'
# vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
# vimcmd_replace_symbol = '[](bold fg:color_purple)'
# vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[character]
disabled = false
format = '[ $symbol  ](bg:color_bg2)'
success_symbol = '[󰣇](bold fg:color_blue bg:color_bg2)'
error_symbol = '[󰣇](bold fg:color_red bg:color_bg2)'
vimcmd_symbol = '[󰣇](bold fg:color_green bg:color_bg2)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple bg:color_bg2)'
vimcmd_replace_symbol = '[](bold fg:color_purple bg:color_bg2)'
vimcmd_visual_symbol = '[](bold fg:color_yellow bg:color_bg2)'
