[flavor]
user = "tokyo-night"

[mgr]
sort_by = "natural"
sort_sensitive = false
sort_die_first = false
sort_translit = true
linemode = "size"
ascrolloff = 10

[preview]
max_width = 2000
max_height = 2000
